# This is a basic workflow to help you get started with Actions

name: Run for test task

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      
      - uses: actions/setup-python@v1

      # Runs a single command using the runners shell
        with:
          python-version: '3.8'
          architecture: 'x64'
        
          
      # Runs a set of commands using the runners shell
#       - name: Run main script
#         run: |
#           python hello_world.py
          
      - name: Run a multi-line script
        run: |
         zip -r test-dep-dev.zip .
    
    #Deploy main.py to AWS
      
      - name: Deploy code to Lambda
        uses: baevres/test_project@master
        with:
          lambda_layer_arn: 'arn:aws:lambda:us-east-2:818687204706:function:hello_world_python3_test'
          lambda_function_name: 'lambda_handler'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
